baseURL = "/"
languageCode = "en-us"
title = "jMonkeyEngine"
paginate=9
summarylength = 60
enableRobotsTXT = true
ignoreErrors = ["error-output-taxonomy"]
pygmentsCodeFences=false

[markup.goldmark.renderer]
  hardWraps = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  hostname="jmonkeyengine.org"

[taxonomies]
  tag = "tags"
  author = "authors"

[outputs]
  home = ["HTML"]
  page = ["HTML","JSON"]
  taxonomy = ["HTML","JSON"]
  term=["HTML","JSON"]

